name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Build and Push to Docker Hub
        run: |
          docker build \
            --build-arg VITE_APIKEY=${{ secrets.VITE_APIKEY }} \
            --build-arg VITE_AUTHDOMAIN=${{ secrets.VITE_AUTHDOMAIN }} \
            --build-arg VITE_PROJECTID=${{ secrets.VITE_PROJECTID }} \
            --build-arg VITE_STORAGEBUCKET=${{ secrets.VITE_STORAGEBUCKET }} \
            --build-arg VITE_MESSAGINGSENDERID=${{ secrets.VITE_MESSAGINGSENDERID }} \
            --build-arg VITE_APPID=${{ secrets.VITE_APPID }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/event-management:latest .
          docker push ${{ secrets.DOCKER_HUB_PASSWORD }}/event-management:latest

      - name: Deploy on WSL2
        run: |
          cd ~/app
          docker compose pull
          docker compose up -d --force-recreate

      - name: Clean up
        run: docker image prune -f